### ISSUE TITLE
test de vérification de la bonne levée d exception si fichier existe pas marche pas

### ISSUE THREAD

**Issue by ben5962** [ben5962/python_planning#1]
> `ERROR:`

>  test_IO_file_operations_filenotfound (test_bdd.testbdd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Utilisateur\Documents\GitHub\python_planning\test_bdd.py", line 253, in test_IO_file_operations_filenotfound
    raise NotImplemented
TypeError: exceptions must derive from BaseException

def test_IO_file_operations_filenotfound(self):
typeerror: exceptions must derive from BaseExceptiondef test_IO_file_operations_filenotfound(self):
        #item 272
        raise NotImplemented
======================================================================
ERROR: tearDownClass (test_bdd.testbdd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Utilisateur\Documents\GitHub\python_planning\test_bdd.py", line 76, in tearDownClass
    raise NotImplemented
TypeError: exceptions must derive from BaseException

**Comment by ben5962** [comment]
nv syntaxe python 3 : les exceptions doivent e générées à partir de la classe exception
def test_IO_file_operations_filenotfound(self):
        #item 272
        raise Exception("une chaine....")

**Comment by ben5962** [comment]
modif envoyée
