### ISSUE TITLE
utiliser un fichier temporaire en écriture, puis en lecture

### ISSUE THREAD

**Issue by ben5962** [ben5962/python_planning#3]
ERROR: setUpClass (test_bdd.testbdd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python36-32\lib\tempfile.py", line 552, in NamedTemporaryFile
    newline=newline, encoding=encoding)
ValueError: must have exactly one of create/read/write/append mode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Utilisateur\Documents\GitHub\python_planning\test_bdd.py", line 66, in setUpClass
    cls.xplode_from_file = tempfile.NamedTemporaryFile(mode='rw', delete=False)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python36-32\lib\tempfile.py", line 556, in NamedTemporaryFile
    _os.unlink(name)
PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\UTILIS~1\\AppData\\Local\\Temp\\tmpmg4c6jaf'

**Comment by ben5962** [comment]
1) create the named temporary file a = tempfile.NamedTemporaryFile(delete=False) default mode: w
2) fill it for i in ["sqsqdf", "qdsfqd", "sqdfqds"]: print(i, a)
3) close it a.close()
4) reopen it like a file but 'r': with open(aa.name) as b:
5) do the read stuff for line in b: print(b)....
6) delete the temporary file :  os.unlink
